version: "3.7"

services:
  redis:
    image: redis
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis

volumes:
  redis:

networks:
  redis:
    driver: bridge
